.TH "Animator" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Modeler\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBWALK\fP = 'null'"
.br
.ti -1c
.RI "std::string \fBBOMB\fP = 'null'"
.br
.ti -1c
.RI "std::string \fBEMOTE\fP = 'null'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string Animator::BOMB = 'null'"

.SS "std::string Animator::EMOTE = 'null'"

.SS "std::string Animator::WALK = 'null'"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
