.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Bomberman/Bomberman.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Bomberman/Bomberman.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'Interfaces/IGame\&.hpp'\fP
.br
\fC#include 'Powerups/Powerups\&.hpp'\fP
.br
\fC#include 'Map/Map\&.hpp'\fP
.br
\fC#include 'Save/Save\&.hpp'\fP
.br
\fC#include 'MotionlessEntity/MotionlessEntity\&.hpp'\fP
.br
\fC#include 'Bomb/Bomb\&.hpp'\fP
.br
\fC#include 'AI/ArtificialIntelligence\&.hpp'\fP
.br
\fC#include 'AI/Astar\&.hpp'\fP
.br
\fC#include 'CFunctions\&.hpp'\fP
.br
\fC#include 'Score/Score\&.hpp'\fP
.br
\fC#include 'Bomberman\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame::Bomberman\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
