.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/Box.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/Box.hpp
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBox\fP { \fBUPPER_LEFT\fP, \fBLOW_LEFT\fP, \fBLOW_RIGHT\fP, \fBUPPER_RIGHT\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBox\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUPPER_LEFT \fP\fP
.TP
\fB\fILOW_LEFT \fP\fP
.TP
\fB\fILOW_RIGHT \fP\fP
.TP
\fB\fIUPPER_RIGHT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
