.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib/Audio Directory Reference" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib/Audio Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAudio\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAudio\&.hpp\fP"
.br
.ti -1c
.RI "file \fBAudio\&.inl\fP"
.br
.in -1c
