.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib Directory Reference" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAudio\fP"
.br
.ti -1c
.RI "directory \fBCamera2D\fP"
.br
.ti -1c
.RI "directory \fBCamera3D\fP"
.br
.ti -1c
.RI "directory \fBCollision2D\fP"
.br
.ti -1c
.RI "directory \fBCollision3D\fP"
.br
.ti -1c
.RI "directory \fBColor\fP"
.br
.ti -1c
.RI "directory \fBCursor\fP"
.br
.ti -1c
.RI "directory \fBDrawing\fP"
.br
.ti -1c
.RI "directory \fBFile\fP"
.br
.ti -1c
.RI "directory \fBFont\fP"
.br
.ti -1c
.RI "directory \fBGamepad\fP"
.br
.ti -1c
.RI "directory \fBImage\fP"
.br
.ti -1c
.RI "directory \fBKeyboard\fP"
.br
.ti -1c
.RI "directory \fBMatrix\fP"
.br
.ti -1c
.RI "directory \fBMouse\fP"
.br
.ti -1c
.RI "directory \fBMusic\fP"
.br
.ti -1c
.RI "directory \fBRectangle\fP"
.br
.ti -1c
.RI "directory \fBRenderTexture\fP"
.br
.ti -1c
.RI "directory \fBShader\fP"
.br
.ti -1c
.RI "directory \fBSound\fP"
.br
.ti -1c
.RI "directory \fBText\fP"
.br
.ti -1c
.RI "directory \fBTexture\fP"
.br
.ti -1c
.RI "directory \fBTiming\fP"
.br
.ti -1c
.RI "directory \fBVector2\fP"
.br
.ti -1c
.RI "directory \fBVector3\fP"
.br
.ti -1c
.RI "directory \fBVector4\fP"
.br
.ti -1c
.RI "directory \fBWindow\fP"
.br
.in -1c
