.TH "Documents/GitHub Directory Reference" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/GitHub Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBB\-YEP\-400\-LYN\-4\-1\-indiestudio\-lucas\&.guichard\fP"
.br
.in -1c
