.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game Directory Reference" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAI\fP"
.br
.ti -1c
.RI "directory \fBAnimated\fP"
.br
.ti -1c
.RI "directory \fBBomb\fP"
.br
.ti -1c
.RI "directory \fBBomberman\fP"
.br
.ti -1c
.RI "directory \fBincludes\fP"
.br
.ti -1c
.RI "directory \fBMap\fP"
.br
.ti -1c
.RI "directory \fBMotionlessEntity\fP"
.br
.ti -1c
.RI "directory \fBPlayer\fP"
.br
.ti -1c
.RI "directory \fBPowerups\fP"
.br
.ti -1c
.RI "directory \fBSave\fP"
.br
.ti -1c
.RI "directory \fBScore\fP"
.br
.in -1c
