.TH "CharDictionary" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharDictionary
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CharDictionary\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBobj\fP"
.br
.ti -1c
.RI "std::string \fBtexture\fP"
.br
.ti -1c
.RI "float \fBscalable\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBRaylib::Color\fP \fBcolor\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBanimations\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> CharDictionary::animations"

.SS "\fBRaylib::Color\fP CharDictionary::color"

.SS "std::string CharDictionary::name"

.SS "std::string CharDictionary::obj"

.SS "float CharDictionary::scalable"

.SS "std::string CharDictionary::texture"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
