.TH "Clock" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Clock\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClock\fP ()"
.br
.ti -1c
.RI "\fB~Clock\fP ()"
.br
.ti -1c
.RI "float \fBgetElapsedTime\fP ()"
.br
.ti -1c
.RI "bool \fBdoesTimeElapsed\fP (const float &time, const bool &reset=true)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Clock::Clock ()"

.SS "Clock::~Clock ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Clock::doesTimeElapsed (const float & time, const bool & reset = \fCtrue\fP)"

.SS "float Clock::getElapsedTime ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
