.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Engine/Core/Core.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Engine/Core/Core.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <istream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'XRay\&.hpp'\fP
.br
\fC#include 'Interfaces/IGraphical\&.hpp'\fP
.br
\fC#include 'Bomberman/Bomberman\&.hpp'\fP
.br
\fC#include 'Interfaces/IGame\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine::Core\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
