.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Game/GameSaveTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Game/GameSaveTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'Save/Save\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGame::Save\fP \fBinitSaveTests\fP ()"
.br
.ti -1c
.RI "\fBTEST\fP (SaveTests, getSettings)"
.br
.ti -1c
.RI "\fBTEST\fP (SaveTests, getPlayers)"
.br
.ti -1c
.RI "\fBTEST\fP (SaveTests, getMap)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBGame::Save\fP initSaveTests ()"

.SS "TEST (SaveTests, getMap)"

.SS "TEST (SaveTests, getPlayers)"

.SS "TEST (SaveTests, getSettings)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
