.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Game/GameMapTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Game/GameMapTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'Map/Map\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (MapTest, pass)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, fail_width_dimension)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, fail_height_dimension)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, fail_player)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, getWidth)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, getHeight)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, setWidth)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, setHeight)"
.br
.ti -1c
.RI "\fBTEST\fP (MapTest, isMapEmpty)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (MapTest, fail_height_dimension)"

.SS "TEST (MapTest, fail_player)"

.SS "TEST (MapTest, fail_width_dimension)"

.SS "TEST (MapTest, getHeight)"

.SS "TEST (MapTest, getWidth)"

.SS "TEST (MapTest, isMapEmpty)"

.SS "TEST (MapTest, pass)"

.SS "TEST (MapTest, setHeight)"

.SS "TEST (MapTest, setWidth)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
