.TH "Game::BombUp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game::BombUp
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Powerups\&.hpp>\fP
.PP
Inherits \fBGame::Powerups\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBombUp\fP (const \fBRaylib::Vector3\fP &position)"
.br
.ti -1c
.RI "\fB~BombUp\fP ()"
.br
.ti -1c
.RI "void \fBapplyPowerupTo\fP (\fBGame::Player\fP &player) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game::BombUp::BombUp (const \fBRaylib::Vector3\fP & position)"

.SS "Game::BombUp::~BombUp ()"

.SH "Member Function Documentation"
.PP 
.SS "void Game::BombUp::applyPowerupTo (\fBGame::Player\fP & player)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBGame::Powerups\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
