.TH "Input" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Input\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGamePadTouch\fP { \fBUP\fP, \fBRIGHT\fP, \fBDOWN\fP, \fBLEFT\fP, \fBTRIANGLE\fP, \fBROND\fP, \fBCROIX\fP, \fBCARRE\fP, \fBL1\fP, \fBL2\fP, \fBR1\fP, \fBR2\fP, \fBSHARE\fP, \fBUNKNOWN\fP, \fBOPTIONS\fP, \fBL3\fP, \fBR3\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInput\fP ()"
.br
.RI "Construct a new \fBInput\fP object\&. "
.ti -1c
.RI "\fB~Input\fP ()"
.br
.RI "Destroy the \fBInput\fP object\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBupdateGamepad\fP ()"
.br
.RI "Get and Set Gamepad \fBInput\fP\&. "
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBInput::GamePadTouch\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUP \fP\fP
.TP
\fB\fIRIGHT \fP\fP
.TP
\fB\fIDOWN \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fITRIANGLE \fP\fP
.TP
\fB\fIROND \fP\fP
.TP
\fB\fICROIX \fP\fP
.TP
\fB\fICARRE \fP\fP
.TP
\fB\fIL1 \fP\fP
.TP
\fB\fIL2 \fP\fP
.TP
\fB\fIR1 \fP\fP
.TP
\fB\fIR2 \fP\fP
.TP
\fB\fISHARE \fP\fP
.TP
\fB\fIUNKNOWN \fP\fP
.TP
\fB\fIOPTIONS \fP\fP
.TP
\fB\fIL3 \fP\fP
.TP
\fB\fIR3 \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Input::Input ()"

.PP
Construct a new \fBInput\fP object\&. 
.SS "Input::~Input ()"

.PP
Destroy the \fBInput\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void Input::updateGamepad ()\fC [static]\fP"

.PP
Get and Set Gamepad \fBInput\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
