.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/PlayerSelector/Map.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/PlayerSelector/Map.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Color/Color\&.hpp'\fP
.br
\fC#include 'Drawing/Drawing\&.hpp'\fP
.br
\fC#include 'Texture/Texture\&.hpp'\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'PlayerSelector/Player\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerSelector::Map\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlayerSelector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
