.TH "md_characters" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_characters \- characters 

.PP
 
.SH "Indie Studio - Time to go cross-platform"
.PP
.IP "\(bu" 2
\fBBinary name:\fP bomberman
.IP "\(bu" 2
\fBLanguage:\fP C++
.IP "\(bu" 2
\fBCompilation:\fP CMake 3\&.17
.PP
.SH "Chararter List"
.PP
.SS "RED"
 
.PP
The fiery leader of the bombermen , Red has a fiery temperament and always follow justice
.SS "BLUE"
 
.PP
The brains of the team , Blue is always lazy but always rises up to the cvhallenges
.SS "YELLOW"
 
.PP
Yellow has a tragic backstory but due to that always strives to make his fellow bombermen happy
.SS "GREEN"
 
.PP
Green is a traitor and secretly works for the evil doctor 
