.TH "md_how_to_play" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_how_to_play \- howToPlay 

.PP
 
.SH "Indie Studio - Time to go cross-platform"
.PP
.IP "\(bu" 2
\fBBinary name:\fP bomberman
.IP "\(bu" 2
\fBLanguage:\fP C++
.IP "\(bu" 2
\fBCompilation:\fP CMake 3\&.17
.PP
.SH "HOW TO PLAY"
.PP
.SS "AIM"
kill as many players as possible and earn the higest number of points
.SS "With keyboards"
Move your character with your directions and place a bomb by pressind on the tab bar
.SS "With mouse"
Move your character using the mouse controler on top of the screen and deop a bomb by leftclicking on the mouse button
.SS "With a controler"
Move your character with your directions and place a bomb by pressind X 
