.TH "md_history" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_history \- history 

.PP
 
.SH "Indie Studio - Time to go cross-platform"
.PP
.IP "\(bu" 2
\fBBinary name:\fP bomberman
.IP "\(bu" 2
\fBLanguage:\fP C++
.IP "\(bu" 2
\fBCompilation:\fP CMake 3\&.17
.PP
.SH "Story"
.PP
The world of bomb was once filled with pecae and happines\&. Till the evil doctor woke the bombermen from their slumber and plan to use their power to destroy the world\&. now our 5 heroes must save the world using the power of friendship and bombe in the famous labyrinths\&. 
