.TH "md_maps" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_maps \- maps 

.PP
 
.SH "Indie Studio - Time to go cross-platform"
.PP
.IP "\(bu" 2
\fBBinary name:\fP bomberman
.IP "\(bu" 2
\fBLanguage:\fP C++
.IP "\(bu" 2
\fBCompilation:\fP CMake 3\&.17
.PP
.SH "Maps List"
.PP
.SS "EARTH KINGDOM"
 
.PP
The prosperous land of the bombermen filled with sunshine and love
.SS "STONE WORLD"
 
.PP
The world inhabited by the evil profesor
.SS "CIVIL WARSHIP BASE"
 
.PP
The human bomberman allince ship which houses the potential to destroy the bomb world
.SS "ICE NEBULA NEXUS"
 
.PP
A piece of the bomb of the orging is said to be frozen somewhere under ths ice of the ice nebule nexus 
