.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/sources/Modeler.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/sources/Modeler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Modeler\&.hpp'\fP
.br
\fC#include 'Exception/Exception\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcatchThrowTrygetAnimationPath\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrygetObjPath\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrygetTexturePath\fP ()"
.br
.ti -1c
.RI "void \fBassertIsThereAnimationsPath\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryupdate\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrymakeWalk\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrymakeBomb\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrymakeEmote\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void assertIsThereAnimationsPath ()"

.SS "int catchThrowTrygetAnimationPath ()"

.SS "int catchThrowTrygetObjPath ()"

.SS "int catchThrowTrygetTexturePath ()"

.SS "int catchThrowTrymakeBomb ()"

.SS "int catchThrowTrymakeEmote ()"

.SS "int catchThrowTrymakeWalk ()"

.SS "int catchThrowTryupdate ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
