.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/Modeler.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/Modeler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'raylib\&.h'\fP
.br
\fC#include 'Clock\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAnimator\fP"
.br
.ti -1c
.RI "class \fBModeler\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFRAMETIME\fP   0\&.03f"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAnimSequence\fP { \fBWALK\fP, \fBBOMB\fP, \fBEMOTE\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FRAMETIME   0\&.03f"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAnimSequence\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWALK \fP\fP
.TP
\fB\fIBOMB \fP\fP
.TP
\fB\fIEMOTE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
