.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/sources/MousePlayerInput.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/sources/MousePlayerInput.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MousePlayerInput\&.hpp'\fP
.br
\fC#include 'Exception/Exception\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcatchThrowTryshouldGoToEast\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldGoToWest\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldGoToNorth\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldGoToSouth\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldChangeToPrev\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldChangeToNext\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryshouldSimulateAClick\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int catchThrowTryshouldChangeToNext ()"

.SS "int catchThrowTryshouldChangeToPrev ()"

.SS "int catchThrowTryshouldGoToEast ()"

.SS "int catchThrowTryshouldGoToNorth ()"

.SS "int catchThrowTryshouldGoToSouth ()"

.SS "int catchThrowTryshouldGoToWest ()"

.SS "int catchThrowTryshouldSimulateAClick ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
