.TH "PlayerSelector" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerSelector
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMap\fP"
.br
.ti -1c
.RI "class \fBPlayer\fP"
.br
.ti -1c
.RI "class \fBSelector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
