.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Powerups/Powerups.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Powerups/Powerups.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Animated/Animated\&.hpp'\fP
.br
\fC#include 'Player/Player\&.hpp'\fP
.br
\fC#include 'Powerups\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame::Powerups\fP"
.br
.ti -1c
.RI "class \fBGame::Life\fP"
.br
.ti -1c
.RI "class \fBGame::Pass\fP"
.br
.ti -1c
.RI "class \fBGame::Fire\fP"
.br
.ti -1c
.RI "class \fBGame::BombUp\fP"
.br
.ti -1c
.RI "class \fBGame::Speed\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
