.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibKeyboardTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibKeyboardTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Tests/Lib/XRaylib/Raylib/Keyboard/Keyboard\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, isKeyPressedTest)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, isKeyDownTest)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, isKeyReleased)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, isKeyUp)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, setExitKeyTest)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, getKeyPressedTest)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, getCharPressedTest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (KeyboardTest, getCharPressedTest)"

.SS "TEST (KeyboardTest, getKeyPressedTest)"

.SS "TEST (KeyboardTest, isKeyDownTest)"

.SS "TEST (KeyboardTest, isKeyPressedTest)"

.SS "TEST (KeyboardTest, isKeyReleased)"

.SS "TEST (KeyboardTest, isKeyUp)"

.SS "TEST (KeyboardTest, setExitKeyTest)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
