.TH "Raylib::Matrix" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Raylib::Matrix
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Matrix\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix\fP (float m0=0, float m1=0, float m2=0, float m3=0, float m4=0, float m5=0, float m6=0, float m7=0, float m8=0, float m9=0, float m10=0, float m11=0, float m12=0, float m13=0, float m14=0, float m15=0)"
.br
.RI "Construct a new \fBMatrix\fP object\&. "
.ti -1c
.RI "\fBMatrix\fP (::\fBMatrix\fP matrix)"
.br
.RI "Construct a new \fBMatrix\fP object\&. "
.ti -1c
.RI "\fBMatrix\fP (const \fBCamera3D\fP &cam)"
.br
.RI "Construct the \fBMatrix\fP object\&. "
.ti -1c
.RI "\fBMatrix\fP (const ::\fBCamera3D\fP &cam)"
.br
.RI "Construct the \fBMatrix\fP object\&. "
.ti -1c
.RI "\fBMatrix\fP (const \fBCamera2D\fP &cam)"
.br
.RI "Construct a new \fBMatrix\fP object\&. "
.ti -1c
.RI "\fBMatrix\fP (const ::\fBCamera2D\fP &cam)"
.br
.RI "Construct a new \fBMatrix\fP objectt\&. "
.ti -1c
.RI "\fB~Matrix\fP ()"
.br
.RI "Destroy the \fBMatrix\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "::\fBMatrix\fP \fB_matrix\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Raylib::Matrix::Matrix (float m0 = \fC0\fP, float m1 = \fC0\fP, float m2 = \fC0\fP, float m3 = \fC0\fP, float m4 = \fC0\fP, float m5 = \fC0\fP, float m6 = \fC0\fP, float m7 = \fC0\fP, float m8 = \fC0\fP, float m9 = \fC0\fP, float m10 = \fC0\fP, float m11 = \fC0\fP, float m12 = \fC0\fP, float m13 = \fC0\fP, float m14 = \fC0\fP, float m15 = \fC0\fP)"

.PP
Construct a new \fBMatrix\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIm0\fP A float 
.br
\fIm1\fP A float 
.br
\fIm2\fP A float 
.br
\fIm3\fP A float 
.br
\fIm4\fP A float 
.br
\fIm5\fP A float 
.br
\fIm6\fP A float 
.br
\fIm7\fP A float 
.br
\fIm8\fP A float 
.br
\fIm9\fP A float 
.br
\fIm10\fP A float 
.br
\fIm11\fP A float 
.br
\fIm12\fP A float 
.br
\fIm13\fP A float 
.br
\fIm14\fP A float 
.br
\fIm15\fP A float 
.RE
.PP

.SS "Raylib::Matrix::Matrix (::\fBMatrix\fP matrix)"

.PP
Construct a new \fBMatrix\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fImatrix\fP A \fBMatrix\fP Object 
.RE
.PP

.SS "Raylib::Matrix::Matrix (const \fBCamera3D\fP & cam)"

.PP
Construct the \fBMatrix\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fImatrix\fP A \fBCamera3D\fP Object 
.RE
.PP

.SS "Raylib::Matrix::Matrix (const ::\fBCamera3D\fP & cam)"

.PP
Construct the \fBMatrix\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fImatrix\fP A \fBCamera3D\fP struct 
.RE
.PP

.SS "Raylib::Matrix::Matrix (const \fBCamera2D\fP & cam)"

.PP
Construct a new \fBMatrix\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIcam\fP A \fBCamera2D\fP Object 
.RE
.PP

.SS "Raylib::Matrix::Matrix (const ::\fBCamera2D\fP & cam)"

.PP
Construct a new \fBMatrix\fP objectt\&. 
.PP
\fBParameters\fP
.RS 4
\fIcam\fP A \fBCamera2D\fP struct 
.RE
.PP

.SS "Raylib::Matrix::~Matrix ()"

.PP
Destroy the \fBMatrix\fP object\&. 
.SH "Member Data Documentation"
.PP 
.SS "::\fBMatrix\fP Raylib::Matrix::_matrix"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
