.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibTextTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibTextTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Tests/Lib/XRaylib/Raylib/Text/Text\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (TextTest, drawTextTest)"
.br
.ti -1c
.RI "\fBTEST\fP (TextTest, measureTextTest)"
.br
.ti -1c
.RI "\fBTEST\fP (TextTest, textIsEqualTest)"
.br
.ti -1c
.RI "\fBTEST\fP (TextTest, textLengthTest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (TextTest, drawTextTest)"

.SS "TEST (TextTest, measureTextTest)"

.SS "TEST (TextTest, textIsEqualTest)"

.SS "TEST (TextTest, textLengthTest)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
