.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibCollision3DTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibCollision3DTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Tests/Lib/XRaylib/Raylib/Collision3D/Collision3D\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionBoundingBoxTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionBoundingBoxFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionBoundingBoxVectorTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionBoundingBoxVectorFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRayVectorTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRayVectorFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRay2VectorTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRay2VectorFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRayBoundingBoxTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision3DTest, checkCollisionRayBoundingBoxFalse)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Collision3DTest, checkCollisionBoundingBoxFalse)"

.SS "TEST (Collision3DTest, checkCollisionBoundingBoxTrue)"

.SS "TEST (Collision3DTest, checkCollisionBoundingBoxVectorFalse)"

.SS "TEST (Collision3DTest, checkCollisionBoundingBoxVectorTrue)"

.SS "TEST (Collision3DTest, checkCollisionFalse)"

.SS "TEST (Collision3DTest, checkCollisionRay2VectorFalse)"

.SS "TEST (Collision3DTest, checkCollisionRay2VectorTrue)"

.SS "TEST (Collision3DTest, checkCollisionRayBoundingBoxFalse)"

.SS "TEST (Collision3DTest, checkCollisionRayBoundingBoxTrue)"

.SS "TEST (Collision3DTest, checkCollisionRayVectorFalse)"

.SS "TEST (Collision3DTest, checkCollisionRayVectorTrue)"

.SS "TEST (Collision3DTest, checkCollisionTrue)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
