.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibCollision2DTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/Raylib/RaylibCollision2DTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Tests/Lib/XRaylib/Raylib/Collision2D/Collision2D\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRadiusRecTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRadiusRecFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRecTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRecFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRadiusTrue)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollisionVectorRadiusFalse)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollision4Vector2False)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollision5Vector2True)"
.br
.ti -1c
.RI "\fBTEST\fP (Collision2DTest, checkCollision5Vector2False)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Collision2DTest, checkCollision4Vector2False)"

.SS "TEST (Collision2DTest, checkCollision5Vector2False)"

.SS "TEST (Collision2DTest, checkCollision5Vector2True)"

.SS "TEST (Collision2DTest, checkCollisionFalse)"

.SS "TEST (Collision2DTest, checkCollisionTrue)"

.SS "TEST (Collision2DTest, checkCollisionVectorFalse)"

.SS "TEST (Collision2DTest, checkCollisionVectorRadiusFalse)"

.SS "TEST (Collision2DTest, checkCollisionVectorRadiusRecFalse)"

.SS "TEST (Collision2DTest, checkCollisionVectorRadiusRecTrue)"

.SS "TEST (Collision2DTest, checkCollisionVectorRadiusTrue)"

.SS "TEST (Collision2DTest, checkCollisionVectorRecFalse)"

.SS "TEST (Collision2DTest, checkCollisionVectorRecTrue)"

.SS "TEST (Collision2DTest, checkCollisionVectorTrue)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
