.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Save/Save.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/Save/Save.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'includes/Settings\&.hpp'\fP
.br
\fC#include 'Player/Player\&.hpp'\fP
.br
\fC#include 'Map/Map\&.hpp'\fP
.br
\fC#include 'Vector3/Vector3\&.hpp'\fP
.br
\fC#include 'Save\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame::Save\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
