.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/includes/Settings.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Game/includes/Settings.hpp
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWorlds\fP { \fBIRON\fP, \fBSNOW\fP, \fBWOOD\fP }"
.br
.ti -1c
.RI "enum \fBSettings\fP { \fBTIMESTAMP\fP, \fBSET_NBR\fP, \fBSET_ID\fP, \fBTIME_GAME\fP, \fBTIME_REMAINING\fP, \fBAI_NBR\fP, \fBAI_LVL\fP, \fBHUMAN_NBR\fP, \fBWORLD\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSettings\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITIMESTAMP \fP\fP
.TP
\fB\fISET_NBR \fP\fP
.TP
\fB\fISET_ID \fP\fP
.TP
\fB\fITIME_GAME \fP\fP
.TP
\fB\fITIME_REMAINING \fP\fP
.TP
\fB\fIAI_NBR \fP\fP
.TP
\fB\fIAI_LVL \fP\fP
.TP
\fB\fIHUMAN_NBR \fP\fP
.TP
\fB\fIWORLD \fP\fP
.SS "enum \fBWorlds\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIRON \fP\fP
.TP
\fB\fISNOW \fP\fP
.TP
\fB\fIWOOD \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
