.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib/Window/Window.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/Raylib/Window/Window.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Window\&.hpp'\fP
.br
\fC#include 'Exception/Exception\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcatchThrowTrywindowShouldClose\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrycloseWindow\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrysetWindowIcon\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTryisWindowFullscreen\fP ()"
.br
.ti -1c
.RI "int \fBcatchThrowTrytoggleFullscreen\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int catchThrowTrycloseWindow ()"

.SS "int catchThrowTryisWindowFullscreen ()"

.SS "int catchThrowTrysetWindowIcon ()"

.SS "int catchThrowTrytoggleFullscreen ()"

.SS "int catchThrowTrywindowShouldClose ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
