.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayGamepadTest.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayGamepadTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Lib/XRaylib/XRay/includes/GamepadPlayerInput\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldGoToEast)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldGoToWest)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldGoToNorth)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldGoToSouth)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldChangeToPrev)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldChangeToNext)"
.br
.ti -1c
.RI "\fBTEST\fP (GamePadTest, shouldSimulateAClick)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (GamePadTest, shouldChangeToNext)"

.SS "TEST (GamePadTest, shouldChangeToPrev)"

.SS "TEST (GamePadTest, shouldGoToEast)"

.SS "TEST (GamePadTest, shouldGoToNorth)"

.SS "TEST (GamePadTest, shouldGoToSouth)"

.SS "TEST (GamePadTest, shouldGoToWest)"

.SS "TEST (GamePadTest, shouldSimulateAClick)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
