.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/XRay.hpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Lib/XRaylib/XRay/includes/XRay.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <string>\fP
.br
\fC#include <array>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'CFunctions\&.hpp'\fP
.br
\fC#include 'IPlayerInput\&.hpp'\fP
.br
\fC#include 'MousePlayerInput\&.hpp'\fP
.br
\fC#include 'KeyboardPlayerInput\&.hpp'\fP
.br
\fC#include 'GamepadPlayerInput\&.hpp'\fP
.br
\fC#include 'Interfaces/IGraphical\&.hpp'\fP
.br
\fC#include 'Camera3D/Camera3D\&.hpp'\fP
.br
\fC#include 'Texture/Texture\&.hpp'\fP
.br
\fC#include 'Window/Window\&.hpp'\fP
.br
\fC#include 'Mouse/Mouse\&.hpp'\fP
.br
\fC#include 'Text/Text\&.hpp'\fP
.br
\fC#include 'Keyboard/Keyboard\&.hpp'\fP
.br
\fC#include 'Color/Color\&.hpp'\fP
.br
\fC#include 'Music/Music\&.hpp'\fP
.br
\fC#include 'Cursor/Cursor\&.hpp'\fP
.br
\fC#include 'Timing/Timing\&.hpp'\fP
.br
\fC#include 'Drawing/Drawing\&.hpp'\fP
.br
\fC#include 'Collision2D/Collision2D\&.hpp'\fP
.br
\fC#include 'Vector2/Vector2\&.hpp'\fP
.br
\fC#include 'Box\&.hpp'\fP
.br
\fC#include 'Cinematic\&.hpp'\fP
.br
\fC#include 'Resources\&.hpp'\fP
.br
\fC#include 'Input\&.hpp'\fP
.br
\fC#include 'PlayerSelector/Player\&.hpp'\fP
.br
\fC#include 'PlayerSelector/Selector\&.hpp'\fP
.br
\fC#include 'Audio/Audio\&.hpp'\fP
.br
\fC#include 'Sound/Sound\&.hpp'\fP
.br
\fC#include 'XRay\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXRay\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
