.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayMousePlayerInputTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayMousePlayerInputTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Lib/XRaylib/XRay/includes/MousePlayerInput\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, GoToEast)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, GoToWest)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, GoToNorth)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, GoToSouth)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, ChangeToPrev)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, ChangeToNext)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBMousePlayerInput\fP, SimulateAClick)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBMousePlayerInput\fP, ChangeToNext)"

.SS "TEST (\fBMousePlayerInput\fP, ChangeToPrev)"

.SS "TEST (\fBMousePlayerInput\fP, GoToEast)"

.SS "TEST (\fBMousePlayerInput\fP, GoToNorth)"

.SS "TEST (\fBMousePlayerInput\fP, GoToSouth)"

.SS "TEST (\fBMousePlayerInput\fP, GoToWest)"

.SS "TEST (\fBMousePlayerInput\fP, SimulateAClick)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
