.TH "C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayKeyboardTests.cpp" 3 "Mon Jun 21 2021" "Version 2.0" "Bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonat/Documents/GitHub/B-YEP-400-LYN-4-1-indiestudio-lucas.guichard/Tests/sources/XRay/XRayKeyboardTests.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include '\&.\&./Lib/XRaylib/XRay/includes/KeyboardPlayerInput\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldGoToEast)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldGoToWest)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldGoToNorth)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldGoToSouth)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldChangeToPrev)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldChangeToNext)"
.br
.ti -1c
.RI "\fBTEST\fP (KeyboardTest, shouldSimulateAClick)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (KeyboardTest, shouldChangeToNext)"

.SS "TEST (KeyboardTest, shouldChangeToPrev)"

.SS "TEST (KeyboardTest, shouldGoToEast)"

.SS "TEST (KeyboardTest, shouldGoToNorth)"

.SS "TEST (KeyboardTest, shouldGoToSouth)"

.SS "TEST (KeyboardTest, shouldGoToWest)"

.SS "TEST (KeyboardTest, shouldSimulateAClick)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bomberman from the source code\&.
