var annotated_dup =
[
    [ "Engine", "namespace_engine.html", [
      [ "Core", "class_engine_1_1_core.html", "class_engine_1_1_core" ],
      [ "Exception", "class_engine_1_1_exception.html", "class_engine_1_1_exception" ]
    ] ],
    [ "Game", "namespace_game.html", [
      [ "ArtificialIntelligence", "class_game_1_1_artificial_intelligence.html", "class_game_1_1_artificial_intelligence" ],
      [ "Point", "class_game_1_1_point.html", "class_game_1_1_point" ],
      [ "Node", "class_game_1_1_node.html", "class_game_1_1_node" ],
      [ "Astar", "class_game_1_1_astar.html", "class_game_1_1_astar" ],
      [ "Animated", "class_game_1_1_animated.html", "class_game_1_1_animated" ],
      [ "Bomb", "class_game_1_1_bomb.html", "class_game_1_1_bomb" ],
      [ "Bomberman", "class_game_1_1_bomberman.html", "class_game_1_1_bomberman" ],
      [ "Map", "class_game_1_1_map.html", "class_game_1_1_map" ],
      [ "MotionlessEntity", "class_game_1_1_motionless_entity.html", "class_game_1_1_motionless_entity" ],
      [ "SolidWall", "class_game_1_1_solid_wall.html", "class_game_1_1_solid_wall" ],
      [ "BreakableWall", "class_game_1_1_breakable_wall.html", "class_game_1_1_breakable_wall" ],
      [ "Floor", "class_game_1_1_floor.html", "class_game_1_1_floor" ],
      [ "Player", "class_game_1_1_player.html", "class_game_1_1_player" ],
      [ "Human", "class_game_1_1_human.html", "class_game_1_1_human" ],
      [ "AI", "class_game_1_1_a_i.html", "class_game_1_1_a_i" ],
      [ "Powerups", "class_game_1_1_powerups.html", "class_game_1_1_powerups" ],
      [ "Life", "class_game_1_1_life.html", "class_game_1_1_life" ],
      [ "Pass", "class_game_1_1_pass.html", "class_game_1_1_pass" ],
      [ "Fire", "class_game_1_1_fire.html", "class_game_1_1_fire" ],
      [ "BombUp", "class_game_1_1_bomb_up.html", "class_game_1_1_bomb_up" ],
      [ "Speed", "class_game_1_1_speed.html", "class_game_1_1_speed" ],
      [ "Save", "class_game_1_1_save.html", "class_game_1_1_save" ],
      [ "Score", "class_game_1_1_score.html", "class_game_1_1_score" ]
    ] ],
    [ "PlayerSelector", "namespace_player_selector.html", [
      [ "Map", "class_player_selector_1_1_map.html", "class_player_selector_1_1_map" ],
      [ "Player", "class_player_selector_1_1_player.html", "class_player_selector_1_1_player" ],
      [ "Selector", "class_player_selector_1_1_selector.html", "class_player_selector_1_1_selector" ]
    ] ],
    [ "Raylib", "namespace_raylib.html", [
      [ "Audio", "class_raylib_1_1_audio.html", "class_raylib_1_1_audio" ],
      [ "Camera2D", "class_raylib_1_1_camera2_d.html", "class_raylib_1_1_camera2_d" ],
      [ "Camera3D", "class_raylib_1_1_camera3_d.html", "class_raylib_1_1_camera3_d" ],
      [ "Collision2D", "class_raylib_1_1_collision2_d.html", "class_raylib_1_1_collision2_d" ],
      [ "Collision3D", "class_raylib_1_1_collision3_d.html", "class_raylib_1_1_collision3_d" ],
      [ "Color", "class_raylib_1_1_color.html", "class_raylib_1_1_color" ],
      [ "Cursor", "class_raylib_1_1_cursor.html", "class_raylib_1_1_cursor" ],
      [ "Drawing", "class_raylib_1_1_drawing.html", "class_raylib_1_1_drawing" ],
      [ "File", "class_raylib_1_1_file.html", "class_raylib_1_1_file" ],
      [ "Font", "class_raylib_1_1_font.html", "class_raylib_1_1_font" ],
      [ "Gamepad", "class_raylib_1_1_gamepad.html", "class_raylib_1_1_gamepad" ],
      [ "Image", "class_raylib_1_1_image.html", "class_raylib_1_1_image" ],
      [ "Keyboard", "class_raylib_1_1_keyboard.html", "class_raylib_1_1_keyboard" ],
      [ "Matrix", "class_raylib_1_1_matrix.html", "class_raylib_1_1_matrix" ],
      [ "Mouse", "class_raylib_1_1_mouse.html", "class_raylib_1_1_mouse" ],
      [ "Music", "class_raylib_1_1_music.html", "class_raylib_1_1_music" ],
      [ "Rectangle", "class_raylib_1_1_rectangle.html", "class_raylib_1_1_rectangle" ],
      [ "RenderTexture", "class_raylib_1_1_render_texture.html", "class_raylib_1_1_render_texture" ],
      [ "Shader", "class_raylib_1_1_shader.html", "class_raylib_1_1_shader" ],
      [ "Sound", "class_raylib_1_1_sound.html", "class_raylib_1_1_sound" ],
      [ "Text", "class_raylib_1_1_text.html", "class_raylib_1_1_text" ],
      [ "Texture", "class_raylib_1_1_texture.html", "class_raylib_1_1_texture" ],
      [ "Timing", "class_raylib_1_1_timing.html", "class_raylib_1_1_timing" ],
      [ "Vector2", "class_raylib_1_1_vector2.html", "class_raylib_1_1_vector2" ],
      [ "Vector3", "class_raylib_1_1_vector3.html", "class_raylib_1_1_vector3" ],
      [ "Vector4", "class_raylib_1_1_vector4.html", "class_raylib_1_1_vector4" ],
      [ "Window", "class_raylib_1_1_window.html", "class_raylib_1_1_window" ]
    ] ],
    [ "Animator", "struct_animator.html", "struct_animator" ],
    [ "CFunctions", "class_c_functions.html", "class_c_functions" ],
    [ "CharDictionary", "struct_char_dictionary.html", "struct_char_dictionary" ],
    [ "Clock", "class_clock.html", "class_clock" ],
    [ "GamepadPlayerInput", "class_gamepad_player_input.html", "class_gamepad_player_input" ],
    [ "IEntity", "class_i_entity.html", "class_i_entity" ],
    [ "IGame", "class_i_game.html", "class_i_game" ],
    [ "IGraphical", "class_i_graphical.html", "class_i_graphical" ],
    [ "Input", "class_input.html", "class_input" ],
    [ "IPlayerInput", "class_i_player_input.html", "class_i_player_input" ],
    [ "KeyboardPlayerInput", "class_keyboard_player_input.html", "class_keyboard_player_input" ],
    [ "Modeler", "class_modeler.html", "class_modeler" ],
    [ "MousePlayerInput", "class_mouse_player_input.html", "class_mouse_player_input" ],
    [ "XRay", "class_x_ray.html", "class_x_ray" ]
];