/*
** EPITECH PROJECT, 2021
** B-YEP-400-LYN-4-1-indiestudio-lucas.guichard
** File description:
** Resources
*/

#ifndef RESOURCES_HPP_
#define RESOURCES_HPP_

typedef enum {
    ADD,
    REMOVE,
    PREVIOUS,
    NEXT,
    CONTROLS,
    GAMEPAD,
    HUMAN,
    AI,
    HEAD,
    LOADGAME_BG,
    LOADGAME,
    LOADGAME_HOVER,
    NEWGAME_BG,
    NEWGAME,
    NEWGAME_HOVER,
    LOADSCENE,
    BRANCH,
    BACK,
    BACK_HOVER,
    HELP,
    HELP_HOVER,
    SETTINGS,
    SETTINGS_HOVER,
    INDIE,
    STUDIO,
    MENU_TITLE,
    BOMBER_TEAM,
    BOMBER_THINKING,
    PLAY,
    PLAY_HOVER,
    QUIT,
    QUIT_HOVER,
    SKIP,
    SKIP_HOVER,
    PARALLAX,
    BG,
    p1,
    p2,
    p3,
    p4,
    P1,
    P2,
    P3,
    P4,
    MOUSEYELLOW,
    KEYBOARDYELLOW,
    PLAYSTATIONYELLOW,
    XBOXYELLOW,
    MOUSEBLUE,
    KEYBOARDBLUE,
    PLAYSTATIONBLUE,
    XBOXBLUE,
    NEXTSCENE,
    NEXT_HOVER,
    MAPCHOICEBG,
    SIZE_HOVER,
    SETS_HOVER,
    DURATION_HOVER,
    AI_HOVER,
    SIZE,
    SETS,
    DURATION,
    IA,
    MOUSEPANEL,
    KEYBOARDPANEL,
    PLAYSTATIONPANEL,
    XBOXPANEL,
    PAUSE,
    DEPAUSE,
    PAUSEBACK,
    RESUME,
    RESTART,
    SAVE,
    SETTING,
    HOME,
    RESUMEHOVER,
    RESTARTHOVER,
    SAVEHOVER,
    SETTINGSHOVER,
    HOMEHOVER,
    SAVED,
    BACKUPBAR,
    VICTORYBG,
    DEFEATBG,
    NEXTLEVEL,
    NEXTLEVELHOVER,
    RANKING,
    UNKNOWN,
    ON,
    OFF,
    SETTING_BG,
    HOWTO_BG,
    VOLUME_UP,
    VOLUME_DOWN,
    LOADINGFRAMEO,
    S7X7S,
    S9X9S,
    S11X11S,
    S13X13S,
    S15X15S,
    S17X17S,
    S19X19S,
    MIN1MIN,
    MIN2MIN,
    MIN3MIN,
    MIN4MIN,
    MIN5MIN,
    SET1SET,
    SET2SET,
    SET3SET,
    SET4SET,
    SET5SET,
    EASY,
    MEDIUM,
    DIFFICULT,
    TEXT_VOLUME,
    TEXT_SFX,
    TEXT_FULLSCREEN,
    TEXT_MUSIC,
    TEXT_GENERAL,
    TEXT_MODS,
    CLOCKBAR,
    YELLOWBOMBERMAN,
    REDBOMBERMAN,
    BLUEBOMBERMAN,
    GREENBOMBERMAN,
    MOUSERADAR,
    BACKUPERROR,
    PRINCE,
    LUCAS,
    JONATHAN,
    NICO,
    MEHDI,
    CHARLES,
    TEAMTITLE,
    SKATE,
    FIRE,
    IBOMB,
    AIPANEL
} Resources;

typedef enum {
    MSC_BOMBERMAN,
    MSC_OPENNING,
    MSC_GAME
} MusicResources;

typedef enum {
    SFX_KLICK,
    SFX_ENTER,
    SFX_SETTING,
    SFX_HOME,
    SFX_NOCK,
    SFX_TURN_OFF,
    SFX_TURN_ON,
    SFX_JIG,
    SFX_JIG1,
    SFX_BING,
    SFX_OPENNING,
    SFX_WEEE,
    SFX_BOOM,
    SFX_TUDUM,
    SFX_DEFEAT,
    SFX_COUNTDOWN
} SfxResources;

#endif /* !RESOURCES_HPP_ */
